### ISSUE TITLE
Handle type array in the DoctrineORMQuerySourceIterator

### ISSUE THREAD

**Issue by rbarilani** [sonata-project/exporter#31]
Hi,

i'm playing with Sonata Admin Bundle, the export feature use this library to output a file  in different formats : json,csv . I saw that "array type" for a doctrine entity is handled by returning $value=null. ([line105 DoctrineORMQuerySourceIterator.php](https://github.com/sonata-project/exporter/blob/master/lib/Exporter/Source/DoctrineORMQuerySourceIterator.php#L105)). So the json exported of an entity that have fields/field of "type array" is not complete. I want to ask why we can't return the array?

**Comment by core23** [comment]
This issue should be fixed in the latest master version. Please have a look at the docs.

If this is still present, feel free to reopen this issue @rbarilani @jpetitcolas

**Comment by zaak** [comment]
@core23; Sorry, but it doesn't look like fixed in current master:

https://github.com/sonata-project/exporter/blob/6dbea3379447f672f46fccd7e29210cc1246aea9/src/Source/DoctrineORMQuerySourceIterator.php#L157-L158

What is the recommended way to define formatting for array field?

**Comment by ns3777k** [comment]
any plans on this?

**Comment by VincentLanglet** [comment]
Do you want to try a PR @ns3777k ?

**Comment by ns3777k** [comment]
My case is I need to export an array of strings, export a boolean value as "yes" / "no" replaced with a translation and be able to call a callback to add or transform some data.

I can give it a try, but since I'm new to sonata I'm not seeing a scalable way to archive this for now  without BC.

To avoid BC a method like `configureExportFields` can be provided that accepts or creates something like `ExportMapper`. This mapper can have multiple methods to manipulate field settings (like add, remove, has, ...), and can be configured to convert any field into any text representation like other mappers.

This mapper then can be passed to a model manager through additional method and then to `DoctrineORMQuerySourceIterator` through `getDataSourceIterator`.

Sounds complicated. What you think? You have any vision on this?

**Comment by VincentLanglet** [comment]
> My case is I need to export an array of strings, export a boolean value as "yes" / "no" replaced with a translation and be able to call a callback to add or transform some data.
> 
> I can give it a try, but since I'm new to sonata I'm not seeing a scalable way to archive this for now without BC.
> 
> To avoid BC a method like `configureExportFields` can be provided that accepts or creates something like `ExportMapper`. This mapper can have multiple methods to manipulate field settings (like add, remove, has, ...), and can be configured to convert any field into any text representation like other mappers.
> 
> This mapper then can be passed to a model manager through additional method and then to `DoctrineORMQuerySourceIterator` through `getDataSourceIterator`.
> 
> Sounds complicated. What you think? You have any vision on this?

It is complicated, but I had the same idea https://github.com/sonata-project/SonataAdminBundle/issues/5854#issuecomment-618113138

I think that indeed that a `configureExportFields` would be great.

BC-way is hard, it should need to create a new interface and a new SourceIterator I think...
